### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by AlexPotterOnGit** [mrmichaelrb/hassio-addons#4]
Hi Michael,

Not sure it is something specific to my environment or some recent changes to Home Assistant - can't install the plugin. Errors in the log:

22-01-15 13:14:59 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/mrmichaelrb/hassio-addons repository
22-01-15 13:15:01 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 2 new - 0 remove
22-01-15 13:15:01 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-01-15 13:15:01 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-01-15 13:15:17 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/423ea876_godaddy_dns
22-01-15 13:15:17 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for 423ea876/amd64-addon-godaddy_dns:1.0.3
22-01-15 13:15:23 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 423ea876/amd64-addon-godaddy_dns:1.0.3: The command '/bin/ash -o pipefail -c apk add --no-cache openssl   && curl -s -o /usr/bin/dehydrated     "https://raw.githubusercontent.com/lukas2511/dehydrated/v${DEHYDRATED_VERSION}/dehydrated"   && chmod a+x /usr/bin/dehydrated' returned a non-zero code: 1
22-01-15 13:15:23 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/12 : ARG BUILD_FROM
Step 2/12 : FROM $BUILD_FROM
 ---> bc9cabb4596e
Step 3/12 : ARG DEHYDRATED_VERSION
 ---> Running in 3a49357c511a
Removing intermediate container 3a49357c511a
 ---> caffde16250f
Step 4/12 : RUN apk add --no-cache openssl   && curl -s -o /usr/bin/dehydrated     "https://raw.githubusercontent.com/lukas2511/dehydrated/v${DEHYDRATED_VERSION}/dehydrated"   && chmod a+x /usr/bin/dehydrated
 ---> Running in 197e7cbc1313
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
140006463986504:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:

fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: Permission denied

140006463986504:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: Permission denied

ERROR: 
unable to select packages:

  openssl (no such package):
    required by: world[openssl]
Removing intermediate container 197e7cbc1313

Wondering if you could give any clues to potential reason?

Cheers

**Comment by mrmichaelrb** [comment]
This is a known problem with running HA on some custom docker hosts (basically anything other than the Home Assistant Operating System) and installing add-ons which require OpenSSL. To fix, update libseccomp2 on the host.

See this thread for more information:
https://community.home-assistant.io/t/supervisor-cant-install-add-ons/301771/15
