### ISSUE TITLE
error running container

### ISSUE THREAD

**Issue by TomK** [mrmichaelrb/hassio-addons#5]
After configuring this addon i'm getting the following error in the logs:
```
s6-overlay-suexec: fatal: can only run as pid 1
```

unfortunately no other information currently

**Comment by TomK** [comment]
presumably related to this https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/ ?

**Comment by robin-vandaele** [comment]
I also have this issue

**Comment by TomK** [comment]
@robin-vandaele i've opened a PR,  if you need to get your certs renewed in the meanwhile, feel free to try it out on my fork  https://github.com/TomK/hassio-addons

**Comment by ericreich** [comment]
@TomK I have tried testing this new fork.  Still getting same error starting the add-on.

**Comment by mrmichaelrb** [comment]
I've been unable to investigate this issue for the last month due to the lack of a HA testing (non-production) platform at my disposal, but I should be able to resume maintenance of these HA add-ons within the next week. Sorry about the delay, but HA had some breaking changes to add-ons in May at a time when I was least prepared to deal with them.

**Comment by ericreich** [comment]
I am using godaddy..

Eric Reich

**Comment by Etienne-Tredoux** [comment]
I am also using the godaddy addon not the google version so if @TomK could do his magic on that addon also it would be appreciated.

**Comment by RobertDiPaolo** [comment]
Using the pull request @TomK made, I've got a version of the godaddy addon working here https://github.com/RobertDiPaolo/hassio-addons if anyone needs it. I can't say I fully understand the changes, I've not doen any addon dev before.

**Comment by TomK** [comment]
@mrmichaelrb @Etienne-Tredoux @RobertDiPaolo i've updated my PR to fix godaddy dns also
